spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shirotest
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    # 连接超时时间（毫秒）
    timeout: 200
    port: 6379
    database: 0
  # jpa\u914D\u7F6E
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform:  org.hibernate.dialect.MySQL57InnoDBDialect  #\u4E0D\u52A0\u8FD9\u53E5\u5219\u9ED8\u8BA4\u4E3Amyisam\u5F15\u64CE
  # \u6A21\u677F\u5F15\u64CE
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # \u7981\u7528\u7F13\u5B58
    cache: false
# \u7528\u6237\u914D\u7F6E
user:
  password:
    # \u5BC6\u7801\u9519\u8BEF{maxRetryCount}\u6B21\u9501\u5B9A10\u5206\u949F
    maxRetryCount: 5

# Shiro
shiro:
  user:
    # \u767B\u5F55\u5730\u5740
    ###主项目写成自己项目的登录页面路径，从项目必须写完成的主项目登录页面url
    loginUrl: /login
    # \u6743\u9650\u8BA4\u8BC1\u5931\u8D25\u5730\u5740
    unauthorizedUrl: /unauth
    # \u9996\u9875\u5730\u5740
    indexUrl: /index
    # \u9A8C\u8BC1\u7801\u5F00\u5173
    captchaEnabled: true
    # \u9A8C\u8BC1\u7801\u7C7B\u578B math \u6570\u7EC4\u8BA1\u7B97 char \u5B57\u7B26
    captchaType: math
  cookie:
    # \u8BBE\u7F6ECookie\u7684\u57DF\u540D \u9ED8\u8BA4\u7A7A\uFF0C\u5373\u5F53\u524D\u8BBF\u95EE\u7684\u57DF\u540D
    domain:
    # \u8BBE\u7F6Ecookie\u7684\u6709\u6548\u8BBF\u95EE\u8DEF\u5F84
    path: /
    # \u8BBE\u7F6EHttpOnly\u5C5E\u6027
    httpOnly: true
    # \u8BBE\u7F6ECookie\u7684\u8FC7\u671F\u65F6\u95F4\uFF0C\u5929\u4E3A\u5355\u4F4D
    maxAge: 30
  session:
    # 毫秒Session\u8D85\u65F6\u65F6\u95F4\uFF08\u9ED8\u8BA430\u5206\u949F\uFF09
    expireTime: 30
    # \u540C\u6B65session\u5230\u6570\u636E\u5E93\u7684\u5468\u671F\uFF08\u9ED8\u8BA41\u5206\u949F\uFF09
    dbSyncPeriod: 1
    # \u76F8\u9694\u591A\u4E45\u68C0\u67E5\u4E00\u6B21session\u7684\u6709\u6548\u6027\uFF0C\u9ED8\u8BA4\u5C31\u662F10\u5206\u949F
    validationInterval: 10

ys:
  # 名称
  name: RuoYi
  # 版本
  version: 3.2.0
  # 版权年份
  copyrightYear: 2019
  # 文件路径
  profile: D:/profile/

  # 获取ip地址开关
  addressEnabled: true

